### ISSUE TITLE
A translation suggestion

### ISSUE THREAD

**Issue by huanghuangge** [MetaCubeX/Clash.Mini#60]
![1](https://user-images.githubusercontent.com/37528193/169516226-547b95cc-eafc-4171-9154-e586b6546df6.png)
![2](https://user-images.githubusercontent.com/37528193/169516228-db7101c4-4e60-419f-95f5-e36c41dccc8b.png)
"Rule Mode" 建议更换 "Proxy Mode"
相应中文 “规则代理” 更换为 “代理模式”

**Comment by akw5454521** [comment]
上有问题，请去 https://github.com/Dreamacro/clash 提请求

**Comment by MetaCubeX** [comment]
好吧，到时调一调
