### ISSUE TITLE
双击托盘or右击托盘控制面板100%闪退

### ISSUE THREAD

**Issue by abbw** [MetaCubeX/Clash.Mini#61]
系统Win10 x64，VC运行库和NET6正常。

百分之百复现此问题，执行此操作后，打开的网址是：

```
http://127.0.0.1:8070/?hostname=127.0.0.1&port=9090&secret=
```

如果手动打开下面该网址则不会闪退

```
http://127.0.0.1:8070
```

**Comment by MetaCubeX** [comment]
@abbw 请安装webview2.0

**Comment by abbw** [comment]
> @abbw 请安装webview2.0

感谢，已解决，不过还是希望后面能不需要这个运行库。用的是Chrome 101.0.4951.67
