### ISSUE TITLE
输入API地址后显示Unauthorized

### ISSUE THREAD

**Issue by Telehub** [MetaCubeX/Clash.Mini#62]
打开软件，输入远程api控制地址，然后显示Unauthorized。
![Unathorized](https://user-images.githubusercontent.com/22582637/169698380-4592cad2-93c6-4ea0-8ef5-49b7fdd8fb02.jpg)

**Comment by MetaCubeX** [comment]
@Telehub mini不是带了托盘吗。。

**Comment by Telehub** [comment]
加了external-controller之后解决了。。感谢
